# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_hcd" "ehci_pci" "ata_piix" "mpt2sas" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e6145e30-eaeb-41b2-ba70-bf244d66e610";
      fsType = "btrfs";
      options = "subvol=root";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e6145e30-eaeb-41b2-ba70-bf244d66e610";
      fsType = "btrfs";
      options = "subvol=home";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d7dd8fd5-5326-48dd-bbfb-7af77bcec429"; }
    ];

  nix.maxJobs = 4;
}
