# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "ums_realtek" "usb_storage" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5c2515dc-6312-47b5-9877-16df06f228fa";
      fsType = "btrfs";
      options = "subvol=nix-root";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5c2515dc-6312-47b5-9877-16df06f228fa";
      fsType = "btrfs";
      options = "subvol=@home";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e40adb5b-6e74-47b7-83ea-bcc13d23752f"; }
    ];

  nix.maxJobs = 2;
}
